services:
  # Laravel application service
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    platform: linux/amd64
    container_name: laravel_app
    working_dir: /var/www/html
    volumes:
      - ../src:/var/www/html  # Updated to mount the 'src' directory containing the Laravel project
      - ./php.local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel_network

  # Nginx service
  nginx:
    image: nginx:alpine
    platform: linux/amd64
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ../src:/var/www/html  # Updated to mount the 'src' directory containing the Laravel project
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel_network
    depends_on:
      - app

  # MySQL service
  db:
    image: mysql:8.0
    platform: linux/amd64
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel_network

  # PhpMyAdmin service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - laravel_network

# Networks
networks:
  laravel_network:
    driver: bridge

# Volumes
volumes:
  mysql_data:
    driver: local
