version: '3.8'

services:
  # Laravel application service
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: your-username/laravel-app:latest 
    container_name: laravel_app
    env_file:
      - ../src/.env  # Path to your .env file
    working_dir: /var/www/html
    volumes:
      - ../src:/var/www/html  # Mount your Laravel app code
    networks:
      - laravel_network
    depends_on:
      - db

  # Nginx service
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"  # HTTPS support
    volumes:
      - ../src:/var/www/html  # Mount the Laravel code
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Use custom Nginx config
      - ./certs:/etc/nginx/certs  # Certificates for SSL/TLS
    networks:
      - laravel_network
    depends_on:
      - app

  # MySQL service
  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: GmailTelegramBot
      MYSQL_USER: GmailTelegramBot
      MYSQL_PASSWORD: #GmailTelegramBot123#
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel_network
    restart: always  

# Networks
networks:
  laravel_network:
    driver: bridge

# Volumes
volumes:
  mysql_data:
    driver: local
